RockHolds image color change script
ARC-Summer-2020/AutoRockClimber pull request #10
Opened 2020-08-19 03:34 UTC by Mars-98

Created script to change image colors, I also cleaned up import code from previous scripts created. 
https://tim-kaufenberg.atlassian.net/browse/ARC-85

2020-08-22 02:56 UTC, coughenberg requested changes

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +        color = Image.merge('RGB', (b, r, g))
Just checking I understand this correctly, you are getting the colors red, green, and blue. Then you are swapping the colors to produce a differently colored image?

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +i = 0
Can you name this variable something more meaningful than i? Also add a comment in the script to what this variable is doing per https://www.python.org/dev/peps/pep-0008/#block-comments

Ex:
`# This is a static variable that contains 'Hello World!' for the print statement.`
`MY_VARIABLE = 'Hello World!'`

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +        #to save the new image as a separate image
Sorry its nitpicky, but space after hashtag

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +i = 0
Also I should note I am personally not very picky about capitalization and complete sentences like pep8 is, but that is just my personal opinion

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +        #play around with the combo of bgr to get different colors
Space after hashtag

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +    if filename.endswith(".jpg"):
Single quotes around .jpg

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +        #hardcode new path, using {0} with format(i+1) to configure new file name
Space after hashtag

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +        color.save("/Users/mary/Documents/PersonalProject/images/file{0}.jpg".format(i+1))
Would you mind actually saving them in a separate folder from the original images for clarity of which is which? Like it will probably be obvious with their colors all switched, but it will still be good practice to keep the originals separate from the altered ones

2020-08-22 02:56 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +    i+=1
Spaces before and after variable assignment operator:
`i += 1`

2020-08-23 21:25 UTC, Mars-98 commented on ImageAugmentation/imageColorAug.py
> +        color = Image.merge('RGB', (b, r, g))
Yes, most pics are made up of channels each individual channel (pixel) is made up of red, green, and blue. Line 16 combines the colors based on the combination of the three you provide, r,g,b or b,r,g, or b,r,r, etc.

2020-08-23 23:38 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +        color = Image.merge('RGB', (b, r, g))
Oh cool!

2020-08-23 23:50 UTC, coughenberg requested changes
Just a Q

2020-08-23 23:50 UTC, coughenberg commented on ImageAugmentation/ImageAugARC1.py
> +    if filename.endswith('.jpg'):
Oh I didn't even see these. Thanks for clean up :)

2020-08-23 23:50 UTC, coughenberg commented on ImageAugmentation/imageColorAug.py
> +            new_img = Image.merge('RGB', (r, g, b))
Now that these are in the order of r,g,b instead of b,r,g, wouldn't it just return the same colors of the photo, then making it an unaltered photo?

2020-08-24 00:17 UTC, coughenberg approved these changes

2020-08-25 00:57 UTC, mr529 approved these changes

2020-08-25 22:55 UTC, merged