Converting electron over to using react
ARC-Summer-2020/AutoRockClimber pull request #3
Opened 2020-07-29 01:42 UTC by skitscha

Just completed the basic conversion of our intial electron code to use react.
Jira Story: https://tim-kaufenberg.atlassian.net/browse/ARC-80

2020-07-29 02:46 UTC, mattshoobs requested changes
Rename div, otherwise looks good.

2020-07-29 02:46 UTC, mattshoobs commented on src/App.tsx
> +const App = () => <div>test2!</div>;
Modify this div, maybe to ARC-UI or something more meaningful.

2020-07-30 22:50 UTC, coughenberg approved these changes

2020-07-31 21:36 UTC, mattshoobs approved these changes

2020-07-31 21:36 UTC, merged