Initial ui changes
ARC-Summer-2020/AutoRockClimber pull request #5
Opened 2020-07-31 22:02 UTC by waterwo2

2020-08-01 17:33 UTC, coughenberg commented
Please add a description to this pr of what you edited, the Jira story this is referencing, and change the title to be more specific on what is being changed per https://github.com/ARC-Summer-2020/AutoRockClimber/wiki/Pull-Review-Expectations

2020-08-02 23:48 UTC, mattshoobs requested changes
Clean up by removing old and unused commented out code then it looks good.

2020-08-02 23:48 UTC, mattshoobs commented on src/App.tsx
> +// import MailIcon from '@material-ui/icons/Mail';
Remove commented out imports that we are not using.

2020-08-02 23:48 UTC, mattshoobs commented on src/App.tsx
> +    padding: theme.spacing(0, 1),
Fine for now, once we display an image I think we will need to increase this or come up with a different solution.

2020-08-02 23:48 UTC, mattshoobs commented on src/App.tsx
> +          tanks or antioxidants. There is no set clinical care of some avenging arrows.
Remove any old commented out code to clean up the file. We wont need the placeholder text.

2020-08-02 23:48 UTC, mattshoobs commented on src/App.tsx
> +          ))}
Remove old commented out code

2020-08-08 16:41 UTC, mattshoobs approved these changes

2020-08-09 01:47 UTC, skitscha approved these changes

2020-08-09 01:48 UTC, merged