Python server endpoint for the rock library
ARC-Summer-2020/AutoRockClimber pull request #7
Opened 2020-08-02 21:23 UTC by coughenberg

Creating the python server endpoints with the import of Bottle for the rock library

https://tim-kaufenberg.atlassian.net/browse/ARC-92

2020-08-02 21:26 UTC, coughenberg commented on .gitignore
> +arcvenv/
Added for .gitignore virtual environment. Already in decision engine

2020-08-03 00:21 UTC, mattshoobs requested changes
Remove unused imports.

2020-08-03 00:21 UTC, mattshoobs commented on rocklibrary/rocklibrary_endpoint/recieve_image_endpoint.py
> +from bottle import run, get, post, request, route, response, abort
Are all these imports used? I don't see get, post, or response used in code.

2020-08-09 01:47 UTC, skitscha approved these changes

2020-08-09 01:50 UTC, skitscha approved these changes

2020-08-10 00:51 UTC, mattshoobs approved these changes

2020-08-10 22:06 UTC, mattshoobs approved these changes

2020-08-10 23:03 UTC, merged