Time testing done
ARC-Summer-2020/AutoRockClimber pull request #8
Opened 2020-08-13 01:30 UTC by PeterX1013

Time test with Dijkstras and with 4 graphs. With graphs of total nodes: 26, 52, 78, and testing with tuples.

2020-08-16 15:51 UTC, coughenberg commented
Can you link the Jira and mention the pull-reviewers in the discord channel please?

2020-08-28 00:01 UTC, coughenberg requested changes

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +
Get rid of spacing between each key of the dictionary please. Also carries on with the other variables so fix those too please

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +
Get rid of this space right after the method definition too

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +class DijkstrasTimeTest(unittest.TestCase):
Move class description underneath the class name and triple quote it like the other DijkstrasTesting file [here](https://github.com/ARC-Summer-2020/AutoRockClimber/blob/decision-engine/decisionengine/dijkstratesting/dijkstras_test.py). Triple quotes are used for docstrings of classes and methods per [PEP257](https://www.python.org/dev/peps/pep-0257/)

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +        self.g2 = {'a': [('aLeft', 3), ('b', 1), ('c', 3)],
Extra line after curly brace, then no space between variable comment and variable. Also space after Hashtag

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +                   'zLeft': [('xLeft', 1), ('wLeft', 1)]
Can replace 'Left' with '0' so it would display 'a0', 'b0'? Left is rather decieving as a variable name here

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +        self.g3 = {'a': [('aLeft', 3),('aRight', 2), ('b', 1), ('c', 3)],
Again with 'Left', should just be able to find and replace all in vsc

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +                   'aRight': [('a', 2),('bRight', 1), ('cRight', 3)],
Change 'Right' to '1' so it will be 'a1', 'b1', etc

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +    def test_graph1(self):
Like the class definition, make the docstring underneath the method name per [PEP257](https://www.python.org/dev/peps/pep-0257/). Same for other methods

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +
Get rid of the extra spacing, it isn't a long enough method to make sense in it being spaced out like this. Same for other methods

2020-08-28 00:01 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +        print(f"Graph 1 Dijkstras Test - 26 nodes {toc - tic:0.4f} seconds")
Instead of an f-string, it looks cleaner to do a String.format().

Ex: `'This is a print statement saying {}'.format('Hello World!')`

2020-08-29 16:54 UTC, coughenberg requested changes

2020-08-29 16:54 UTC, coughenberg commented on decisionengine/dijkstratesting/time_test.py
> +        self.g4 = {(1,1): [((1,2),1)],
Make a comment on this variable too, and double check that all the other comments have a space after the hashtag then I'll approve it

2020-09-01 03:29 UTC, coughenberg approved these changes

2020-09-01 21:06 UTC, skitscha approved these changes

2020-09-01 21:06 UTC, merged